apiVersion: v1
kind: PersistentVolume
metadata:
  name: triton-models-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/hdd/models
