apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: local-l2
spec:
  nodeSelector:
    matchLabels:
      name: worker1
  interfaces:
    - enp6s0
  externalIPs: true
  loadBalancerIPs: true
