apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: local-l2
spec:
  nodeSelector:
    matchLabels:
      l2candidate: "true"
  interfaces:
    - enp1s0
    - enp2s0
    - enp3s0
    - enp4s0
    - enp5s0
    - enp6s0
  externalIPs: true
  loadBalancerIPs: true
