apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: db
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/hdd/pgdata
