apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: db
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: postgres
      labels:
        app: postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker1 # dta-server
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:15.15-alpine3.22
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-password
                  key: password
          ports:
            - containerPort: 5432
              name: postgres-conn
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc
---

