
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volumes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fudoge/kube-manifests-lab.git
    targetRevision: main
    path: infra/storage
  destination:
    server: https://kubernetes.default.svc
  syncPolicy: {}
